version: '3.8'

services:
  backend:
    build: ./backend
    restart: always
    ports:
      - "127.0.0.1:3001:8000"
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - WEB_APP_URL=${WEB_APP_URL}
    env_file:
      - .env
